baseURL = 'https://ashwinyue.github.io/hugo-demo/'
languageCode = 'zh-cn'
title = '我的Hugo博客'
theme = 'PaperMod'

[params]
  author = "Your Name"
  description = "这是我的Hugo博客"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "欢迎来到我的博客"
  Content = "这里是我分享技术和生活的地方"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/ashwinyue"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 50
