baseURL = 'https://ashwinyue.github.io/hugo-demo/'
languageCode = 'zh-cn'
title = '我的Hugo博客'
theme = 'PaperMod'

# Hugo性能优化
summaryLength = 150

# 分页配置
[pagination]
  pagerSize = 10
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

# 构建优化
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# 语法高亮配置
[markup]
  [markup.highlight]
    style = 'github-dark'
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    anchorLineNos = false
    lineAnchors = ""
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# SEO优化
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  author = "Your Name"
  description = "这是我的Hugo博客，分享技术心得与生活感悟"
  keywords = ["Hugo", "博客", "技术", "编程", "前端"]
  
  # 功能开关
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true
  
  # 主题设置
  defaultTheme = "auto"
  disableThemeToggle = false
  
  # 性能优化
  env = "production"

[params.homeInfoParams]
  Title = "欢迎来到我的博客"
  Content = "这里是我分享技术和生活的地方"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/ashwinyue"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 50
